steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/ai360-260519/ai360/backend:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/ai360-260519/ai360/backend:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'ai360-backend'
    - '--image=us-central1-docker.pkg.dev/ai360-260519/ai360/backend:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--service-account=1085838555720-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "ai360-260519"
  _SERVICE_NAME: "ai360-backend"
